### ISSUE TITLE
Inlude `batteryMode` as entity

### ISSUE THREAD

**Issue by goebelmeier** [marq24/ha-evcc#1]
### Description

If `batteryDischargeControl` is activated, there is a JSON element `batteryMode` which can be `normal`, `hold` or `charge`

Due to the fact that i'm using this information for HA automations, it would be nice to have them available in your integration and drop custom MQTT entities

**Comment by marq24** [comment]
Please check out the new release - and the corresponding release notes (specially when you want to get the actual evcc codes)... If this solves the issue - please be so kind and close it - TIA
