### ISSUE TITLE
EVCC Status ändert sich in Home Assistant aber HA kann nicht EVCC Status ändern

### ISSUE THREAD

**Issue by MrMattn** [marq24/ha-evcc#18]
### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

I have noticed, that when I change the status in EVCC, from out to (for example) PV or Quick, it's change in Home Assistant.
But if I change the status in Home Assistant, nothing happens in EVCC.

Here a video: https://youtu.be/zS9fI792XpY

**Comment by marq24** [comment]
Please provide debug log output - could be that write operation from HA to evcc is failing... Therefore I need the logging - when you modify the selection in HA

**Comment by MrMattn** [comment]
[Uploading home-assistant_evcc_intg_2024-08-28T15-43-51.712Z.log…]()


hilft dir das weiter?

**Comment by marq24** [comment]
"das" was hier bislang in Github angekommen ist hilft mir bislang nicht weiter :-D [da ist zwar ein link in Deinem post - aber irgendwie kein Content]

**Comment by marq24** [comment]
at least here local with latest evcc 130.6 and ha 2024.8.3 there is no issue at all... "works fine in my office"

**Comment by MrMattn** [comment]
hilft dir der dropbox link weiter?
https://www.dropbox.com/scl/fi/9bi2o8eebjgbebki8fto6/home-assistant_evcc_intg_2024-08-28T15-43-51.712Z.log?rlkey=8sjlyc0gcoua8r2asmcsem2u1&dl=0

hier ist die log Datei.

**Comment by marq24** [comment]
the URL you entered in the setup is "invalid" - you have entered a '/' after the port - this is the root cause of your issue

**Comment by MrMattn** [comment]
oha and how or where can I change this? :-(

**Comment by marq24** [comment]
remove the ConfigEntry and just add it again...

https://github.com/marq24/ha-evcc/issues/12

**Comment by MrMattn** [comment]
ok thank you I will do this.
Where do I have to do that?
under Settings Integrations? Or under HACS?

**Comment by marq24** [comment]
![image](https://github.com/user-attachments/assets/5301e337-edcb-4a30-853f-9d436459089b)

**Comment by MrMattn** [comment]
it worked. thank you very much!

**Comment by MrMattn** [comment]
Hi I need your help again.
The problem is back.
I remembered your tip here and removed EVCC and reinstalled it.
I left out "/" at the end of the URL.
But the problem keeps coming up.
The status changes to "PV" every now and then.

How can I create or find this log file that you need?

**Comment by marq24** [comment]
https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md

**Comment by marq24** [comment]
but probably either evcc and/or the integration are again not up2date...

**Comment by MrMattn** [comment]
I think you're right. I should check that first. EVCC is up to date in HA but not in proxmox in the VM in which EVCC is installed.

If I open EVCC I see the version v0.124.6.

Unfortunately I don't know the command how I can update EVCC in the console in Proxmox
