### ISSUE TITLE
Add support for Homebattery -> Load From Grid

### ISSUE THREAD

**Issue by MarcelMertens** [marq24/ha-evcc#19]
### Description

With the latest release EVCC supports load from grid based on energy prices for the home battery (simmilar to the car battery).
![image](https://github.com/user-attachments/assets/161da1bc-fc35-4c8b-bb79-8ca8486aba79)

Any chance to add this?

Kind Regards

### API Keys

```shell
0,12€ -> POST /api/batterygridchargelimit/0.12
-0,03€ -> POST /api/batterygridchargelimit/-0.035
```

**Comment by marq24** [comment]
sure - should not be a big deal - thanks for let me know!

**Comment by marq24** [comment]
update to https://github.com/marq24/ha-evcc/releases/tag/2024.9.1

**Comment by marq24** [comment]
@MarcelMertens can we close this?

**Comment by MarcelMertens** [comment]
yes, thank you!

**Comment by bjornenvall** [comment]
no, it doesn't work because it has a maximal of:

min: -0.05
max: 0.45
step: 0.005
mode: box
unit_of_measurement: SEK/kWh
icon: mdi:cash-multiple
friendly_name: "Home-Battery: grid charging SEK limit ≤"

how can change this?

**Comment by bjornenvall** [comment]
<img width="588" alt="Skärmavbild 2025-01-02 kl  13 59 02" src="https://github.com/user-attachments/assets/ddca6efd-9ed3-408f-813e-3cffaea898ad" />

**Comment by bjornenvall** [comment]
i want to raise the max value.

**Comment by marq24** [comment]
so if you want to enter values > 45 ct/kWh then `native_max_value=0.45` must be adjusted

**Comment by bjornenvall** [comment]
yeah, i understand that, how do i do that? as i wrote i tried it, what should i do after?, because it doesn't change in ha. the sensor keeps it old max value. is it in more files other than  const.py?

**Comment by marq24** [comment]
let me try to create/provide a fix (that will use 10x of the default max value, if currency is not EUR)

**Comment by bjornenvall** [comment]
Okey. So I cant change the value in the file?
Thanks!

**Comment by marq24** [comment]
you can - but you need to restart ha that the change will take effect... (and there are two cost limit's that should be adjusted)... fix will be there in 15sec...

**Comment by bjornenvall** [comment]
It works! Thanks!

**Comment by bjornenvall** [comment]
Hi again..
Now only missing the way to turn it off. Or as it’s called in evcc, “none”.
