### ISSUE TITLE
Allow currency selection for entities

### ISSUE THREAD

**Issue by JamesW-AU** [marq24/ha-evcc#37]
### Description

Similar to https://github.com/evcc-io/evcc/issues/16880 , I noticed that the currency entities show values in Euro, rather than (relevant for me) dollars. Would it be please be possible to provide this as a settable option?

**Comment by JamesW-AU** [comment]
Disregard - stats have changed from € to "AUD" after installing evcc v0.131.3

**Comment by loryanstrant** [comment]
I have this issue now. Freshly installed EVCC running 0.200.9, HA 2025.2.1.
Tariffs are set to AUD in EVCC but show as € in HA.

![Image](https://github.com/user-attachments/assets/5c7d3e99-237f-4025-9f7a-9f3f44d376c2)

![Image](https://github.com/user-attachments/assets/ad7a89ad-562c-4c14-9d0b-5448c84e4a20)

It does however show as AUD here:

![Image](https://github.com/user-attachments/assets/8cf6e661-35ec-4717-9e40-0617bfcdd39c)

**Comment by marq24** [comment]
Hi - I am not able to reproduce here the issue ?!

![Image](https://github.com/user-attachments/assets/c1bc40f1-b80c-4e16-9859-f3716c599b4b)

can you simply remove the integration - and re-add it again - if this still fails, then I would need the debug log output from the HA start... TIA

**Comment by loryanstrant** [comment]
Odd, it went away after a HA reboot - which had been done previously.
Oh well, thanks anyway!
