### ISSUE TITLE
Mismatch of current selection between EVCC itself and this integration?

### ISSUE THREAD

**Issue by marq24** [marq24/ha-evcc#4]
### Discussed in https://github.com/marq24/ha-evcc/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **MortuuS** June  3, 2024</sup>
Hi!
First of all thanks for this integration. But I think I found a bug, or I am misunderstanding something?

In the dropdown menu of 'charging current max' the selections range from 0.125A to **14A**. While the dropdown menu in EVCC goes from 6A to 32A. 
Similar problem with 'charging current min' this integration goes from 6A to 32A. While EVCC goes from 0.125A to **16A**
So these inputs seem switched to me? And also the upper limit for minimum current seems incorrect (14A vs 16A).

![Screenshot 2024-06-03 172958](https://github.com/marq24/ha-evcc/assets/6415298/e3848bd9-19e0-4546-ae39-1452c6de765e)
![Screenshot 2024-06-03 173031](https://github.com/marq24/ha-evcc/assets/6415298/defa091c-52df-434d-a465-3d5ec68ce703)

Thanks again. 👍 </div>

**Comment by MortuuS** [comment]
Updated to build 2024.6.0. This fixed the issue mentioned above.
Thanks again for the quick fix. :)
