### ISSUE TITLE
Support grid charging settings

### ISSUE THREAD

**Issue by andreas-bulling** [marq24/ha-evcc#51]
### Description

It would be fantastic if the integration allowed to read/set the different grid charging settings, e.g. the "price limit", "Fast charge from home battery" etc

This is currently not possible IMHO

![image](https://github.com/user-attachments/assets/29d0e06f-3752-4d17-83d6-8df9b3dc4cdb)

**Comment by marq24** [comment]
Mahlzeit! Da es in evcc so viele unterschiedliche Schalter/Optionen gibt, ist es (zumindest für mich) nicht immer ersichtlich von welchen evcc optionen gesprochen wird. Ein Screenshot aus evcc der das entsprechenden Setting zeigt macht es deutlich einfacher vor verstehen, wovon Du sprichst/was Du meinst... 

Desweiteren sollte man wissen, das nicht alle verfügbaren HA-Entities per Default aktiviert sind und man diese erst noch für die Integration in HA aktivieren muss.

**Comment by andreas-bulling** [comment]
Hi, sorry, dachte Grid Charging ist so zentral, dass ein Screenshot nicht notwendig ist. Habe einen ergänzt.

**Comment by UDicke** [comment]
> to read/set the different grid charging settings, e.g. the "price limit", "Fast charge from home battery" etc

Hallo @andreas-bulling ,
folgende Entitäten sind von der "evcc" Hausbatterie:
![grafik](https://github.com/user-attachments/assets/413ad17b-c4e1-4256-8361-51fa6f4c3395)

Zum Setzten vom Preislimit schau mal hier: [https://github.com/marq24/ha-evcc/discussions/24](https://github.com/marq24/ha-evcc/discussions/24)

Alle anderen Entitäten sind "evcc Konfiguration" und nicht zum direkten Steuern geeignet. Preislimit eigentlich auch, das hat aber nach Setzen sofort Wirkung und Netzladen wird aktiviert oder deaktiviert genau wie beim Setzen des Preislimits in evcc.

**Comment by marq24** [comment]
Nun - wie @UDicke schon sagt - so was offensichtliches gibt es seit dem ersten Tag - such mal nach `number.????_smart_cost_limit` bzw eben `number.evcc_battery_grid_charge_limit`... 

Keine Ahnung, wieso diese Wert bei Dir ggf nicht auftauchen?!

**Comment by bjornenvall** [comment]
no, it doesn't work because  it has a maximal of:

min: -0.05
max: 0.45
step: 0.005
mode: box
unit_of_measurement: SEK/kWh
icon: mdi:cash-multiple
friendly_name: "Home-Battery: grid charging SEK limit ≤"

how can change this?
