### ISSUE TITLE
cannot start evcc, protocol state that it cannot find evcc.yaml

### ISSUE THREAD

**Issue by virtualkknight** [marq24/ha-evcc#53]
### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

I´m not able to start the the evcc program as I get following message: 
Using config file: config/evcc.yaml
Config not found. Please create a config under config/evcc.yaml.
For details see evcc documentation at https://github.com/evcc-io/evcc#readme.

The evcc.yaml file exists as I created it, but it seems that the program does not find it.
what do I do wrong?

### Add your DEBUG log output

```shell
Using config file: config/evcc.yaml
Config not found. Please create a config under config/evcc.yaml.
For details see evcc documentation at https://github.com/evcc-io/evcc#readme.
```

**Comment by marq24** [comment]
well - this integration of course requires a working evcc installation...
